version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service:
    build: ./users-service
    container_name: users_service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
      - users-service/.env
    volumes:
      - ./shared:/shared
      - ./users-service/app:/app/app
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  products-service:
    build: ./products-service
    container_name: products_service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
      - products-service/.env
    volumes:
      - ./shared:/shared
      - ./products-service/app:/app/app
    ports:
      - "8002:8002"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload

  orders-service:
    build: ./orders-service
    container_name: orders_service
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
      - orders-service/.env
    volumes:
      - ./shared:/shared
      - ./orders-service/app:/app/app
    ports:
      - "8003:8003"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload

volumes:
  postgres_data:
